### ISSUE TITLE
migrate error

### ISSUE THREAD

**Issue by xialuo1990** [jly8866/archer#2]
环境：
python：3.4
django：1.8
mysql : 5.4.42
self.server_version = '5.6.24-72.2-log'

python3 manage.py migrate
python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/commands/makemigrations.py", line 63, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 317, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration sql.0001_initial dependencies reference nonexistent parent node ('auth', '0007_alter_validators_add_error_messages')
[inception@vm_yw_20160927h archer-master]$ python3 manage.py makemigrations sql
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/commands/makemigrations.py", line 63, in handle
    loader = MigrationLoader(None, ignore_no_migrations=True)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 321, in build_graph
    _reraise_missing_dependency(migration, parent, e)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 291, in _reraise_missing_dependency
    raise exc
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 317, in build_graph
    self.graph.add_dependency(migration, key, parent)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/graph.py", line 116, in add_dependency
    parent
django.db.migrations.graph.NodeNotFoundError: Migration sql.0001_initial dependencies reference nonexistent parent node ('auth', '0007_alter_validators_add_error_messages')
[inception@vm_yw_20160927h archer-master]$ python3 manage.py migrate
Traceback (most recent call last):
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1053, in _read_query_result
    result.read()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1337, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/core/management/commands/migrate.py", line 93, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/executor.py", line 19, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 47, in __init__
    self.build_graph()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/loader.py", line 191, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/recorder.py", line 59, in applied_migrations
    self.ensure_schema()
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/migrations/recorder.py", line 53, in ensure_schema
    editor.create_model(self.Migration)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/base/schema.py", line 286, in create_model
    self.execute(sql, params or None)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/base/schema.py", line 111, in execute
    cursor.execute(sql, params)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/usr/local/python36/lib/python3.4/site-packages/Django-1.8.17-py3.4.egg/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 852, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1053, in _read_query_result
    result.read()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1337, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/python36/lib/python3.4/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")
尝试了很久，一直报这个错误

**Comment by jly8866** [comment]
推荐使用mysql 5.6以及以上，5.4 5.5都可能会有这个问题

**Comment by Lydia92** [comment]
django.db.utils.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL)' at line 1")

最后这个问题，是因为MySQL版本的原因 之前的版本不支持datetime(6)等这种类型
